### ISSUE TITLE
Large-scale Offshore Wind Farm Electrical Collector System Planning: A Mixed-Integer Linear Programming Approach. (arXiv:2108.08569v1 [eess.SY])

### ISSUE THREAD

**Issue by CoffeeKumazaki** [CoffeeKumazaki/arXiv#10078]
Large-scale Offshore Wind Farm Electrical Collector System Planning: A Mixed-Integer Linear Programming Approach. (arXiv:2108.08569v1 [eess.SY])<br>
https://ift.tt/3D0XUYo<br>
<p>In this paper, we propose a planning method for large-scale offshore wind farm (OWF) electrical collector system (ECS) based on mixed integer linear programming, in which the sizing and siting of offshore substations and the lines between wind turbines (WTs) are optimized. We found out that the problem is similar to power distribution system planning, where the topological constraints for distribution network expansion planning (DNEP) are applied to guarantee the radiality of ECS topology and accelerate the solving process. Case studies based on an OWF with 63 fixed-locations WTs demonstrate the effectiveness of proposed method, in which the cost of ECS's investment on cables is reduced by 23%, power loss reduced by 44% compared with a conventional design, and the calculation time reduced with the help of the radiality constraint.</p>
<br>
<br>
via eess.SY updates on arXiv.org http://arxiv.org/<br>

**Comment by bananaexcelsior** [comment]
How can I download this program please?

**Comment by bananaexcelsior** [comment]
你好 ，请问一下我能下载这个程序吗？

**Comment by CoffeeKumazaki** [comment]
https://arxiv.org/abs/2108.08569

The program does not seem to be publicly available. Please ask the authors.

**Comment by bananaexcelsior** [comment]
OK. Thank you.
