### ISSUE TITLE
Incrementally Stochastic and Accelerated Gradient Information mixed Optimization for Manipulator Motion Planning. (arXiv:2108.09490v1 [cs.RO])

### ISSUE THREAD

**Issue by CoffeeKumazaki** [CoffeeKumazaki/arXiv#10180]
Incrementally Stochastic and Accelerated Gradient Information mixed Optimization for Manipulator Motion Planning. (arXiv:2108.09490v1 [cs.RO])<br>
https://ift.tt/3zcIwWL<br>
<p>This paper introduces a novel motion planning algorithm, incrementally stochastic and accelerated gradient information mixed optimization (iSAGO), for robotic manipulators in a narrow workspace. Primarily, we propose the overall scheme of iSAGO integrating the accelerated and stochastic gradient information for efficient descent in the penalty method. In the stochastic part, we generate the adaptive stochastic moment via the random selection of collision checkboxes, interval time-series, and penalty factor based on Adam to solve the body-obstacle stuck case. Due to the slow convergence of STOMA, we integrate the accelerated gradient and stimulate the descent rate in a Lipschitz constant reestimation framework. Moreover, we introduce the Bayesian tree inference (BTI) method, transforming the whole trajectory optimization (SAGO) into an incremental sub-trajectory optimization (iSAGO) to improve the computational efficiency and success rate. Finally, we demonstrate the key coefficient tuning, benchmark iSAGO against other planners (CHOMP, GPMP2, TrajOpt, STOMP, and RRT-Connect), and implement iSAGO on AUBO-i5 in a storage shelf. The result shows the highest success rate and moderate solving efficiency of iSAGO.</p>
<br>
<br>
via cs.RO updates on arXiv.org http://arxiv.org/<br>

**Comment by hello-starry** [comment]
where is the code？
