### ISSUE TITLE
Integrated and Adaptive Guidance and Control for Endoatmospheric Missiles via Reinforcement Learning. (arXiv:2109.03880v1 [eess.SY])

### ISSUE THREAD

**Issue by CoffeeKumazaki** [CoffeeKumazaki/arXiv#10725]
Integrated and Adaptive Guidance and Control for Endoatmospheric Missiles via Reinforcement Learning. (arXiv:2109.03880v1 [eess.SY])<br>
https://ift.tt/2YCwRTr<br>
<p>We apply the meta reinforcement learning framework to optimize an integrated and adaptive guidance and flight control system for an air-to-air missile, implementing the system as a deep neural network (the policy). The policy maps observations directly to commanded rates of change for the missile's control surface deflections, with the observations derived with minimal processing from the computationally stabilized line of sight unit vector measured by a strap down seeker, estimated rotational velocity from rate gyros, and control surface deflection angles. The system induces intercept trajectories against a maneuvering target that satisfy control constraints on fin deflection angles, and path constraints on look angle and load. We test the optimized system in a six degrees-of-freedom simulator that includes a non-linear radome model and a strapdown seeker model. Through extensive simulation, we demonstrate that the system can adapt to a large flight envelope and off nominal flight conditions that include perturbation of aerodynamic coefficient parameters and center of pressure locations. Moreover, we find that the system is robust to the parasitic attitude loop induced by radome refraction, imperfect seeker stabilization, and sensor scale factor errors. Finally, we compare our system's performance to two benchmarks: a proportional navigation guidance system benchmark in a simplified 3-DOF environment, which we take as an upper bound on performance attainable with separate guidance and flight control systems, and a longitudinal model of proportional navigation coupled with a three loop autopilot. We find that our system moderately outperforms the former, and outperforms the latter by a large margin.</p>
<br>
<br>
via eess.SY updates on arXiv.org http://arxiv.org/<br>

**Comment by hqtang-git** [comment]
Hello, thanks for your great job, can you privide me with your six degrees-of-freedom simulator that includes a non-linear radome model and a strapdown seeker model.
