### ISSUE TITLE
Distributed Extended Object Tracking Information Filter Over Sensor Networks. (arXiv:2111.02098v2 [eess.SY] UPDATED)

### ISSUE THREAD

**Issue by CoffeeKumazaki** [CoffeeKumazaki/arXiv#13163]
Distributed Extended Object Tracking Information Filter Over Sensor Networks. (arXiv:2111.02098v2 [eess.SY] UPDATED)<br>
https://ift.tt/3CIMqIE<br>
<p>Motivated by the two common limitations on current distributed extended object tracking systems, i.e., an object is observable by each node, and its extent is modeled as an ellipse, this paper considers a multiplicative error model (MEM) to design the distributed information filter (IF) over a realistic network. The MEM reduces the extent of perpendicular axis-symmetric objects into a 3-D vector, which causes MEM being a nonlinear and state-coupled model with multiplicative noise. To meet the requirement in IF that the state-space model is a linear model with additive noise, we derive two separate pseudo-linearized models by using the first-order Taylor series expansion. The separation is merely in form, and the cross-correlation between states is preserved as parameters in each other's model. Thus, the joint estimation is transferred into an iterative operation of two linear filters. The two models is then applied to propose a centralized IF, where the measurements are converted into a summation of innovation parts. Later, under a sensor network with the communication nodes and sensor nodes, we present two distributed IFs based on the consensus on information and consensus on measurement schemes, respectively. Simulations indicate the performance of the proposed filters w.r.t accuracy, convergence, and consistency.</p>
<br>
<br>
via eess.SY updates on arXiv.org http://arxiv.org/<br>

**Comment by lzfwan150789** [comment]
Thank you for following our work that gives a distributed extended object tracking information filter. Recently, we have submitted the latest version into arXiv [https://arxiv-export1.library.cornell.edu/abs/2111.02098v4](url).
