### ISSUE TITLE
Towards a Hybrid RF/Optical Lunar Communication System (LunarComm). (arXiv:2203.15899v1 [eess.SY])

### ISSUE THREAD

**Issue by CoffeeKumazaki** [CoffeeKumazaki/arXiv#17436]
Towards a Hybrid RF/Optical Lunar Communication System (LunarComm). (arXiv:2203.15899v1 [eess.SY])<br>
https://ift.tt/gwbldT3<br>
<p>The prospect of mankind returning to the Moon has garnered a great amount of attention in recent years. Dozens of lunar missions are planned for the coming decade which will require the development of a sustainable communication infrastructure with high data rates and minimal latency. Space communication systems thus far have relied on Radio Frequency (RF) links alone, but recent developments in laser communications have demonstrated that Free Space Optical (FSO) links can achieve much higher data rates. Upon considering the respective benefits and drawbacks of RF and FSO links, we make a case for the integration of these two technologies into a hybrid RF/FSO lunar communications architecture which leverages small satellites in a Low Earth Orbit (LEO) constellation. We include a case study for this technology designed in Analytical Graphics Systems Tool Kit (STK) software. Results are presented in terms of chain access duration, propagation delay, transmission loss, Signal-to-Noise Ratio (SNR), and Bit Error Rate (BER). This architecture shows potential to revolutionize extraterrestrial communications and pave the way for highly ambitious future missions in space.</p>
<br>
<br>
via eess.SY updates on arXiv.org http://arxiv.org/<br>

**Comment by zhengkunpeng** [comment]
May I ask how to create the earth constellation and the moon constellation in a scene of STK to realize the communication between the earth orbiting satellite and the moon? I want to add the earth constellation and the moon constellation, and achieve the communication function between the constellation and the constellation, now I do not know how to achieve it.
