### ISSUE TITLE
Deep Interactive Motion Prediction and Planning: Playing Games with Motion Prediction Models. (arXiv:2204.02392v1 [cs.RO])

### ISSUE THREAD

**Issue by CoffeeKumazaki** [CoffeeKumazaki/arXiv#17635]
Deep Interactive Motion Prediction and Planning: Playing Games with Motion Prediction Models. (arXiv:2204.02392v1 [cs.RO])<br>
https://ift.tt/RCB597N<br>
<p>In most classical Autonomous Vehicle (AV) stacks, the prediction and planning layers are separated, limiting the planner to react to predictions that are not informed by the planned trajectory of the AV. This work presents a module that tightly couples these layers via a game-theoretic Model Predictive Controller (MPC) that uses a novel interactive multi-agent neural network policy as part of its predictive model. In our setting, the MPC planner considers all the surrounding agents by informing the multi-agent policy with the planned state sequence. Fundamental to the success of our method is the design of a novel multi-agent policy network that can steer a vehicle given the state of the surrounding agents and the map information. The policy network is trained implicitly with ground-truth observation data using backpropagation through time and a differentiable dynamics model to roll out the trajectory forward in time. Finally, we show that our multi-agent policy network learns to drive while interacting with the environment, and, when combined with the game-theoretic MPC planner, can successfully generate interactive behaviors.</p>
<br>
<br>
via cs.RO updates on arXiv.org http://arxiv.org/<br>

**Comment by aerocraft696** [comment]
give me code

**Comment by mayichao1999** [comment]
give me code too

**Comment by git0929** [comment]
Is there a code, please
