### ISSUE TITLE
Technical Report for Argoverse2 Challenge 2022 -- Motion Forecasting Task. (arXiv:2206.07934v1 [cs.CV])

### ISSUE THREAD

**Issue by CoffeeKumazaki** [CoffeeKumazaki/arXiv#20058]
Technical Report for Argoverse2 Challenge 2022 -- Motion Forecasting Task. (arXiv:2206.07934v1 [cs.CV])<br>
https://ift.tt/uw9hU2F<br>
<p>We propose a motion forecasting model called BANet, which means Boundary-Aware Network, and it is a variant of LaneGCN. We believe that it is not enough to use only the lane centerline as input to obtain the embedding features of the vector map nodes. The lane centerline can only provide the topology of the lanes, and other elements of the vector map also contain rich information. For example, the lane boundary can provide traffic rule constraint information such as whether it is possible to change lanes which is very important. Therefore, we achieved better performance by encoding more vector map elements in the motion forecasting model.We report our results on the 2022 Argoverse2 Motion Forecasting challenge and rank 2nd on the test leaderboard.</p>
<br>
<br>
via cs.RO updates on arXiv.org http://arxiv.org/<br>

**Comment by Cram3r95** [comment]
Hi @CoffeeKumazaki, amazing work. Do you have any documentation or code about how you compute the most plausible lanes around the vehicle?
