### ISSUE TITLE
Auto-Encoder-Extreme Learning Machine Model for Boiler NOx Emission Concentration Prediction. (arXiv:2206.14496v1 [cs.LG])

### ISSUE THREAD

**Issue by CoffeeKumazaki** [CoffeeKumazaki/arXiv#20442]
Auto-Encoder-Extreme Learning Machine Model for Boiler NOx Emission Concentration Prediction. (arXiv:2206.14496v1 [cs.LG])<br>
https://ift.tt/ZARGLyv<br>
<p>An automatic encoder (AE) extreme learning machine (ELM)-AE-ELM model is proposed to predict the NOx emission concentration based on the combination of mutual information algorithm (MI), AE, and ELM. First, the importance of practical variables is computed by the MI algorithm, and the mechanism is analyzed to determine the variables related to the NOx emission concentration. Then, the time delay correlations between the selected variables and NOx emission concentration are further analyzed to reconstruct the modeling data. Subsequently, the AE is applied to extract hidden features within the input variables. Finally, an ELM algorithm establishes the relationship between the NOx emission concentration and deep features. The experimental results on practical data indicate that the proposed model shows promising performance compared to state-of-art models.</p>
<br>
<br>
via eess.SY updates on arXiv.org http://arxiv.org/<br>

**Comment by AIXIE** [comment]
Can you share your code and dataset for this article?

**Comment by Xiu-233** [comment]
Can you share the code and dataset of this article?
