### ISSUE TITLE
Paving the Way Towards Mobile IAB: Problems Solutions and Challenges. (arXiv:2206.14946v1 [eess.SY])

### ISSUE THREAD

**Issue by CoffeeKumazaki** [CoffeeKumazaki/arXiv#20521]
Paving the Way Towards Mobile IAB: Problems, Solutions and Challenges. (arXiv:2206.14946v1 [eess.SY])<br>
https://ift.tt/fIqnWad<br>
<p>Deploying access and backhaul as wireless links, a.k.a. integrated access and backhaul (IAB), is envisioned as a viable approach to enable flexible and dense networks. Even further, mobile IAB (mIAB) is a candidate solution to enhance the connectivity of user equipments (UEs) moving together. In this context, different of other works from the literature, the present work overviews the basis for the deployment of mIAB by presenting: 1) the current status of IAB standardization in the fifth generation (5G) new radio (NR); 2) a new taxonomy for state-of-the-art works regarding fixed IAB and mIAB; 3) an extensive performance analysis of mIAB based on simulation results; and 4) open challenges and potential future prospects of mIAB. Specifically, the proposed taxonomy classifies IAB works according to different perspectives and categorizes mIAB works according to the type of mobility. For each type of mobility, the main studied topics are presented. Regarding the performance evaluation, we consider an urban macro scenario where mIAB nodes are deployed in buses in order to improve the passengers connection. The results show that, compared to other network architectures, the deployment of mIAB nodes remarkably improves the passengers throughput and latency in both downlink and uplink.</p>
<br>
<br>
via eess.SY updates on arXiv.org http://arxiv.org/<br>

**Comment by Singularities-and-bubbles** [comment]
is there any demo that this article can refer to? I can not understand how to model the uplink of the IAB donor nodes in heterogeneous networks.
