### ISSUE TITLE
A Flexible MATLAB/Simulink Simulator for Robotic Floating-base Systems in Contact with the Ground. (arXiv:2211.09716v1 [cs.RO])

### ISSUE THREAD

**Issue by CoffeeKumazaki** [CoffeeKumazaki/arXiv#23651]
A Flexible MATLAB/Simulink Simulator for Robotic Floating-base Systems in Contact with the Ground. (arXiv:2211.09716v1 [cs.RO])<br>
https://ift.tt/oZ8DENt<br>
<p>Physics simulators are widely used in robotics fields, from mechanical design to dynamic simulation, and controller design. This paper presents an open-source MATLAB/Simulink simulator for rigid-body articulated systems, including manipulators and floating-base robots. Thanks to MATLAB/Simulink features like MATLAB system classes and Simulink function blocks, the presented simulator combines a programmatic and block-based approach, resulting in a flexible design in the sense that different parts, including its physics engine, robot-ground interaction model, and state evolution algorithm are simply accessible and editable. Moreover, through the use of Simulink dynamic mask blocks, the proposed simulation framework supports robot models integrating open-chain and closed-chain kinematics with any desired number of links interacting with the ground. The simulator can also integrate second-order actuator dynamics. Furthermore, the simulator benefits from a one-line installation and an easy-to-use Simulink interface.</p>
<br>
<br>
via cs.RO updates on arXiv.org http://arxiv.org/<br>

**Comment by RCBird** [comment]
I can't find the toolbox on GitHub, Can you tell me where I could get it? Thank you.

**Comment by RCBird** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，邮件已收到，谢谢。

**Comment by CoffeeKumazaki** [comment]
I couldn't find it in their repositories, either. So it might still be a private repository. Please ask the authors.

**Comment by RCBird** [comment]
OK，thank you！



---Original---
From: "Kohei ***@***.***&gt;
Date: Sun, Nov 20, 2022 00:22 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [CoffeeKumazaki/arXiv] A Flexible MATLAB/Simulink Simulator forRobotic Floating-base Systems in Contact with the Ground. (arXiv:2211.09716v1[cs.RO]) (Issue #23651)




 
I couldn't find it in their repositories, either. So it might still be a private repository. Please ask the authors.
