### ISSUE TITLE
Modeling Degradation for Second-life Battery: Preliminary Results. (arXiv:2102.03715v1 [eess.SY])

### ISSUE THREAD

**Issue by CoffeeKumazaki** [CoffeeKumazaki/arXiv#3522]
Modeling Degradation for Second-life Battery: Preliminary Results. (arXiv:2102.03715v1 [eess.SY])<br>
https://ift.tt/3tEJ9Wz<br>
<p>This paper presents a novel battery modeling framework based on the enhanced single particle model (ESPM) to account for degradation mechanisms of second-life batteries. While accounting for the transport and electrochemical phenomena in the battery solid and electrolyte phases, the dominant anode-related aging mechanisms, namely, solid electrolyte interphase (SEI) layer growth and lithium plating, are modeled. For the first time, the loss of active material (LAM), which describes the tendency of anode and cathode, over time, to reduce the electrode material available for intercalation and deintercalation, is introduced in the ESPM. Moreover, the coupling of the aging modes with the LAM dynamics provides a comprehensive framework that can be employed for the prediction of both linear and non-linear capacity fade crucial to assess second-life battery. Thus, relying on data borrowed from [18], a model parameter identification and a comprehensive sensitivity analysis are performed to prove the effectiveness of the modeling approach.</p>
<br>
<br>
via eess.SY updates on arXiv.org http://arxiv.org/<br>

**Comment by ShivamAMR** [comment]
Is there a simulink model available?

**Comment by CoffeeKumazaki** [comment]
Hi there. It seems not to be available.
