### ISSUE TITLE
Optimal Distributed Frequency and Voltage Control for Zonal Electricity Markets. (arXiv:2102.07949v1 [math.OC])

### ISSUE THREAD

**Issue by CoffeeKumazaki** [CoffeeKumazaki/arXiv#3747]
Optimal Distributed Frequency and Voltage Control for Zonal Electricity Markets. (arXiv:2102.07949v1 [math.OC])<br>
https://ift.tt/3pnqxqB<br>
<p>Zonal pricing is a well-suited mechanism to incentivize grid-supporting behavior of profit-maximizing producers and consumers operating on a large-scale power system. In zonal electricity markets, local system operators create individual price zones, which provide appropriate price signals depending on local grid conditions such as an excess or shortage of electrical energy in certain regions. In this paper, a continuous-time zonal pricing controller for AC power networks is presented that ensures frequency and voltage stability as well as Pareto efficiency of the resulting closed-loop equilibria. Based on a dynamic network model taking into account line losses and power exchange with adjacent price zones, distributed control laws are derived which require only neighbor-to-neighbor communication. Case studies on the IEEE-57 bus system with different pricing concepts illustrate how zonal prices enable consideration of regional supply and demand conditions as well as increased robustness compared to an isolated grid operation.</p>
<br>
<br>
via eess.SY updates on arXiv.org http://arxiv.org/<br>

**Comment by Rekeanu** [comment]
Hi, I am very interested in this article you posted, could you please show me the code? thanks very much.
