### ISSUE TITLE
Analysis of a 3-RUU Parallel Manipulator. (arXiv:2103.09037v1 [cs.RO])

### ISSUE THREAD

**Issue by CoffeeKumazaki** [CoffeeKumazaki/arXiv#4751]
Analysis of a 3-RUU Parallel Manipulator. (arXiv:2103.09037v1 [cs.RO])<br>
https://ift.tt/30PLl0b<br>
<p>The aim of this paper is to give a detailed examination of the input and output singularities of a 3-RUU parallel manipulator in the translational operation mode. This task is achieved by using algebraic constraint equations. For this type of manipulator a complete workspace representation in Study coordinates is presented after elimination of the input parameters. Both, input and output singularities are mapped into a Study subspace as well as into the joint space. Therewith a detailed singularity investigation of the translational operation mode of a 3-RUU parallel manipulator is provided. This paper is an extended version of a previous publication. The addendum comprises the discovery of a possible transition between two operation modes as well as a self motion and an examination of another component of the output singularity surface, most of them for arbitrary design parameters.</p>
<br>
<br>
via cs.RO updates on arXiv.org http://arxiv.org/<br>

**Comment by arashrasouli** [comment]
Hello doctor
Good time
Can you help me simulate this article?
I did some of the simulation, but the algorithm I designed fails when the robot goes to singular points.

thank you
